- name: Create user
  become: true
  user:
    name: "{{ user_username }}"
    create_home: true
    shell: /usr/bin/bash
    append: yes
    groups:
      - adm
      - cdrom
      - sudo
      - dip
      - video
      - plugdev
      - input
      - lpadmin
      - lxd
      - luis
      - sambashare
      - docker
      - vboxusers
      - microk8s
